### ISSUE TITLE
Get the actual Frame when there are Drop Shadows and outer Borders

### ISSUE THREAD

**Issue by angusjune** [sketch-hq/SketchAPI#585] opened 2019-07-25 13:31 UTC
Is it possible to get the actual Frame **if a component has drop shadows and outer borders**?

For example a Rectangle with `frame = { x: 0, y: 0, width: 100, height: 100 }` and `1px` outer Border, its "actual frame" is `{ x: -1, y: -1, width: 102, height: 102 }`.

**Comment by bomberstudios** [comment] 2019-11-18 21:35
This will be fixed when we implement #655

**Comment by christianklotz** [comment] 2019-12-20 09:30
Closing as a duplicate of #655.

**Closed by christianklotz** 2019-12-20 09:30 UTC
