### ISSUE TITLE
Docs for particular versions?

### ISSUE THREAD

**Issue by corysimmons** [sketch-hq/SketchAPI#690] opened 2019-12-20 02:28 UTC
Please add the ability to change docs for particular versions of Sketch. For instance, I have Sketch53 and would love to work on a plugin for it, but I'm certain the docs only show the API for the latest version.

Every other platform that exposes an API typically has some sort of select box that allows you to pick the version of docs you'd like to read so you know what you're trying should/shouldn't work.

**Comment by christianklotz** [comment] 2019-12-20 09:06
👍 on the request, closing this one though since duplicate of #411.

**Closed by christianklotz** 2019-12-20 09:06 UTC
