### ISSUE TITLE
Confusion about Shared Styles on Layer

### ISSUE THREAD

**Issue by KevinGutowski** [sketch-hq/SketchAPI#667] opened 2019-11-08 05:54 UTC
Many people seemed to be confused (myself included) that you set and get a shared style from

```layer.sharedStyle```

See
- https://sketchplugins.com/d/1807-how-can-i-find-out-if-a-layer-style-deviates-from-its-shared-style
- https://sketchplugins.com/d/1810-how-to-get-shared-style-of-symbol-override

Can the documentation be updated so that is properly communicated?

**Comment by mathieudutour** [comment] 2019-11-08 16:14
Duplicate of https://github.com/sketch-hq/SketchAPI/issues/327

**Comment by christianklotz** [comment] 2019-12-19 17:18
Closing since it's a duplicate.

**Closed by christianklotz** 2019-12-19 17:18 UTC
